# Generated by Django 3.1.5 on 2022-03-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infrared',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('infrared_data', models.CharField(max_length=100)),
            ],
        ),
    ]
