# Generated by Django 3.1.5 on 2022-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrared',
            name='get_data_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
