# Generated by Django 3.1.5 on 2022-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_infrared_get_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('images_data', models.ImageField(upload_to='')),
                ('get_data_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ultrasonic',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ultrasonic_data', models.CharField(max_length=100)),
                ('get_data_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
